### ISSUE TITLE
required field marked as optional

### ISSUE THREAD

**Issue by codectl** [SupImDos/pydantic-argparse#34]
I got the following model

```python
Arg(BaseModel):
    f = Field(default=os.environ.get("F"),  description="description of F", required=True)
```

The field is marked as optional even though I provide him with ```required``` option. I know I have to remove the default option but I would like to force it to be required.

Otherwise is there a chance to include a field to read variables from ```env``` ?

**Comment by kytta** [comment]
> The field is marked as optional even though I provide him with `required` option. I know I have to remove the default option but I would like to force it to be required.

But why define the default if you're expecting the user to provide it anyway?

**Comment by SupImDos** [comment]
Hi @codectl, sorry for the long wait - I have been on holiday over the new year.

I did originally have intentions of supporting environment variables in some way (e.g., using `pydantic.BaseSettings`), but I tend to agree with @kytta. I'm not sure if it makes sense to have a default value while also expecting the user to provide one.

I'll do some thinking regarding environment variables at some point and get back to this with what I think the expected behaviour should be.

**Comment by SupImDos** [comment]
Current behaviour of environment variables using `pydantic.BaseSettings` is probably as I would expect for optional arguments:

`example.py`
```python
# Third-Party
import pydantic
import pydantic_argparse

# Typing
from typing import Optional


# Note the usage of `BaseSettings` instead of `BaseModel`
class Arguments(pydantic.BaseSettings):
    """Simple Command-Line Arguments."""
    # Required Args
    flag: bool = pydantic.Field(description="a required flag")

    # Optional Args
    integer: Optional[int] = pydantic.Field(None, description="a required integer")
    string: Optional[str] = pydantic.Field(None, description="a required string")


def main() -> None:
    """Simple Main Function."""
    # Create Parser and Parse Args
    parser = pydantic_argparse.ArgumentParser(
        model=Arguments,
        prog="Example Program",
        description="Example Description",
        version="0.0.1",
        epilog="Example Epilog",
    )
    args = parser.parse_typed_args()

    # Print Args
    print(args)


if __name__ == "__main__":
    main()
```

```shell
$ python example.py --flag
flag=True integer=None string=None

$ export INTEGER=42
$ export STRING=hello
$ python example.py --flag
flag=True integer=42 string='hello'
```

Not sure how we could handle required arguments at this stage though.

**Comment by SupImDos** [comment]
A possibly elegant solution would be to just bypass `argparse.ArgumentParser`'s checks altogether, and delegate all validation to the `pydantic` model. This would allow environment variables to be loaded automatically by the `pydantic.BaseSettings` _before_ the "required" flag is checked. We can still group arguments by `required` and `optional` in the help message.

This can all be done with a 1 line change:
https://github.com/SupImDos/pydantic-argparse/blob/master/pydantic_argparse/argparse/parser.py#L180
```diff
-         if kwargs.get(ArgumentParser.KWARG_REQUIRED):
+         if kwargs.pop(ArgumentParser.KWARG_REQUIRED):
```

The only affect I can think of that this would have is on the help message displayed:

_Before_:
```bash
$ python example.py
usage: Example Program [-h] [-v] --number NUMBER [--integer INTEGER] [--string STRING]
Example Program: error: the following arguments are required: --number

$ export NUMBER=1.23
$ python example.py
usage: Example Program [-h] [-v] --number NUMBER [--integer INTEGER] [--string STRING]
Example Program: error: the following arguments are required: --number
```

_After_:
```bash
$ python example.py
usage: Example Program [-h] [-v] [--number NUMBER] [--integer INTEGER] [--string STRING]
Example Program: error: 1 validation error for Arguments
number
  field required (type=value_error.missing)

$ export NUMBER=1.23
$ python example.py
number=1.23 integer=None string=None
```

This might be a good change moving forward regardless. We can always write our own method to display the `pydantic.ValidationError` exception using the `.errors()` method.

**TODO**: I haven't tested this with nested models yet.

**Comment by SupImDos** [comment]
Closed in https://github.com/SupImDos/pydantic-argparse/pull/41, released in [v0.8.0](https://github.com/SupImDos/pydantic-argparse/releases/tag/v0.8.0) ([PyPI](https://pypi.org/project/pydantic-argparse/0.8.0/))

**Comment by ericchansen** [comment]
Am I correct in understanding that .env files are not supported as they are in Pydantic?

**Comment by SupImDos** [comment]
@ericchansen Good question. If they're not supported currently then I think they should be - that was always the intention anyway. I'll open a new issue so we can check this out properly.
